# You can create more language files to use, or just change messages_en.yml directly
language: en

# Whether to activate mod detection
enable: true

# Whether to print logs to console
# Enabling this will show every mod and plugin messages (yes, it actually shows some plugin messages and player mod channeling messages) between your players and your server in console
# Notice: This would be helpful to show all mods that a server can get so that you can easily add more forbidden mods if you want.
logger: true

# Use custom kick command instead of default kick player
useCustomKickCommand: true

# Custom kick command if enabled (supports %player% and %kickMessage%)
command: "kick %player% %kickMessage%"

# Keywords to identify forbidden mods from plugin message channels
# And it's better to add ""
forbiddenList:
  - "fabric"
  - "forge"
  - "xaeroworldmap"
  - "xaerominimap"
  - "worldinfo"
  - "tweakeroo"
  - "creativecore"
  - "minimapsync"
  - "servux"
  - "axiom"
  - "freecam"
  - "flashback"
  - "voxelmap"
  - "replay"
